spring:
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none